include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/Flutter/ephemeral/**
    - ios/.symlinks/**
    - macos/Flutter/ephemeral/**
    - "**/SourcePackages/**"

linter:
  rules: