// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQNpHEdAm9n2EMiWjP992dJkD3a-9gmE',
    appId: '1:303991226345:android:71e15743455021fc1e5578',
    messagingSenderId: '303991226345',
    projectId: 'sawitify',
    storageBucket: 'sawitify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMh6WIi8N7EK0pMw6r-CfjT6H06M5GTTo',
    appId: '1:303991226345:ios:dcdb48df5c9420351e5578',
    messagingSenderId: '303991226345',
    projectId: 'sawitify',
    storageBucket: 'sawitify.firebasestorage.app',
    iosBundleId: 'com.sawitify.sawitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMh6WIi8N7EK0pMw6r-CfjT6H06M5GTTo',
    appId: '1:303991226345:ios:dcdb48df5c9420351e5578',
    messagingSenderId: '303991226345',
    projectId: 'sawitify',
    storageBucket: 'sawitify.firebasestorage.app',
    iosBundleId: 'com.sawitify.sawitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIXMeSh8cueQRhIOCA-CwTfS-OonqiUc',
    appId: '1:303991226345:web:d2b02c532c87efc81e5578',
    messagingSenderId: '303991226345',
    projectId: 'sawitify',
    authDomain: 'sawitify.firebaseapp.com',
    storageBucket: 'sawitify.firebasestorage.app',
    measurementId: 'G-R75T3GEK2Z',
  );
}
